# Site settings
baseurl = "https://www.gokhanciflikli.com/"
languageCode = "en"
title = "Computational Social Science"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-90951528-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[params]
	name = "Gokhan Ciflikli"
	job = "Computational Social Science"
	description = "Data Science, Visualization, Machine Learning, R, Python"
	bio = "[R](https://gokhanciflikli.com/categories/r) | [Python](https://gokhanciflikli.com/categories/python) | [Visualization](https://gokhanciflikli.com/categories/visualization) | [Prediction](https://gokhanciflikli.com/categories/prediction)"

	github = "ciflikli"
	enableRSS = true
	
	title404 = "This is not the web page you are looking for."
	subtitle404 = "Perhaps your father wanted you to browse this page when you were old enough, but your uncle wouldn't allow it. He feared you might follow old Obi-Wan on some damn fool idealistic crusade like your father did..."

	disqusShortname = "gokhancif"
	enableDisqus = true

	enableGoogleAnalytics = true

	custom_css = []
	customJS  = []

	aboutAuthor = "Computational Social Scientist"

	iconFont = "font-awesome"
  
  shareOnTwitter = true

  shareOnFacebook = true

#[social]
 # github-square = "https://github.com/ciflikli"
