# Site settings
baseurl = "https://gokhan.netlify.com/"
languageCode = "en"
title = "Computational Social Science"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-90951528-1"
hasCJKLanguage = false
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
PygmentsUseClasses = true

[params]
	name = "Gokhan Ciflikli"
	job = "Computational Social Science"
	description = "Computational Social Science, Data Science, Visualization, Machine Learning, R, Python"
	bio = "R | Shiny Apps | Data Visualization | ML | Python"

	github = "ciflikli"
	enableRSS = false

	# Disqus comment
	disqusShortname = "gokhancif"
	enableDisqus = true

	# Enable googleAnalytics
	enableGoogleAnalytics = true

	# Add custom assets with their paths relative to the static folder
	custom_css = []
	customJS  = []

	# Sharing options and author information in posts
	aboutAuthor = "Computational Social Scientist"

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""
  
  shareOnTwitter = true

  shareOnFacebook = true

[social]
  github-square = "https://github.com/ciflikli"
